### ISSUE TITLE
AnsorMed maketini sarlavhasida xatolik bor.

### ISSUE THREAD

**Issue by NodirXon0609** [Andarov/ansormed#1]
https://github.com/Andarov/ansormed/blob/8e83edd3effdb722777225a690c2830fd2ecb09c/index.html#L7
Title'da Ansor Med so'zlarini orasiga probel qo'yib qo'ygansiz, AnsorMed kabi probelsiz yozilishi kerak.

**Comment by Andarov** [comment]
fill issue #1
